// Auto-generated by scripts/build-photo-wall.mjs — do not edit by hand.
export type PhotoWallImage = {
  src: string
  alt: string
  width: number
  height: number
}

export const portraitPhotos: PhotoWallImage[] = [
  {
    "src": "/images/new-photos/00-extra-photos/2-Weighting-in.jpeg",
    "alt": "Weighting in",
    "width": 1884,
    "height": 4029
  },
  {
    "src": "/images/dish-3401.jpg",
    "alt": "dish 3401",
    "width": 1500,
    "height": 2000
  },
  {
    "src": "/images/dishes/plating-3164.jpg",
    "alt": "plating 3164",
    "width": 1500,
    "height": 2000
  },
  {
    "src": "/images/new-photos/Catching-Crayfish.jpg",
    "alt": "Catching Crayfish",
    "width": 1500,
    "height": 2000
  },
  {
    "src": "/images/process-3109.jpg",
    "alt": "process 3109",
    "width": 1500,
    "height": 2000
  },
  {
    "src": "/images/kitchen-3343.jpg",
    "alt": "kitchen 3343",
    "width": 1500,
    "height": 2000
  },
  {
    "src": "/images/table-3007.jpg",
    "alt": "table 3007",
    "width": 1500,
    "height": 2000
  },
    {
    "src": "/images/new-photos/Heading-to-dock.jpg",
    "alt": "Heading to dock",
    "width": 2337,
    "height": 3622
  },

]

export const landscapePhotos: PhotoWallImage[] = [
  {
    "src": "/images/catch-1346.jpg",
    "alt": "catch 1346",
    "width": 2000,
    "height": 1500
  },
  {
    "src": "/images/catch-3092.jpg",
    "alt": "catch 3092",
    "width": 2000,
    "height": 1500
  },
  {
    "src": "/images/cured-salmon.jpg",
    "alt": "cured salmon",
    "width": 2000,
    "height": 1336
  },
  {
    "src": "/images/dish-3421.jpg",
    "alt": "dish 3421",
    "width": 2000,
    "height": 1500
  },
  {
    "src": "/images/dish-3428.jpg",
    "alt": "dish 3428",
    "width": 1999,
    "height": 1442
  },
  {
    "src": "/images/dishes/4-Crispy-skin-rainbow-trout.jpeg",
    "alt": "Crispy skin rainbow trout",
    "width": 4032,
    "height": 3024
  },
  {
    "src": "/images/dishes/Cream-based-salmon-chowder-2.jpg",
    "alt": "Cream based salmon chowder 2",
    "width": 4032,
    "height": 3024
  },
  {
    "src": "/images/dishes/Cream-based-salmon-chowder.jpg",
    "alt": "Cream based salmon chowder",
    "width": 4032,
    "height": 3024
  },
  {
    "src": "/images/dishes/Local-Lobster-mushrooms.jpg",
    "alt": "Local Lobster mushrooms",
    "width": 4032,
    "height": 3024
  },
  {
    "src": "/images/dishes/Rainbow-trout.jpg",
    "alt": "Rainbow trout",
    "width": 4032,
    "height": 3024
  },
  {
    "src": "/images/dishes/Risotto-2.jpg",
    "alt": "Risotto 2",
    "width": 4032,
    "height": 3024
  },
  {
    "src": "/images/dishes/Simple-dark-rye-salmon-breakfast.jpg",
    "alt": "Simple dark rye salmon breakfast",
    "width": 4032,
    "height": 3024
  },
  {
    "src": "/images/kitchen-2620.jpg",
    "alt": "kitchen 2620",
    "width": 2000,
    "height": 1500
  },
  {
    "src": "/images/new-photos/00-extra-photos/Duck-fritatta.jpg",
    "alt": "Duck fritatta",
    "width": 4032,
    "height": 3024
  },
  {
    "src": "/images/new-photos/00-extra-photos/More-vegetables.jpg",
    "alt": "More vegetables",
    "width": 4032,
    "height": 3024
  },
  {
    "src": "/images/new-photos/00-extra-photos/Preparing-Roe.jpg",
    "alt": "Preparing Roe",
    "width": 4032,
    "height": 3024
  },
  {
    "src": "/images/new-photos/00-extra-photos/Risotto-2.jpg",
    "alt": "Risotto 2",
    "width": 4032,
    "height": 3024
  },
  {
    "src": "/images/new-photos/00-extra-photos/Smoked-Perfection-2.jpg",
    "alt": "Smoked Perfection 2",
    "width": 4032,
    "height": 3024
  },
  {
    "src": "/images/new-photos/00-extra-photos/duck-sausage.jpg",
    "alt": "duck sausage",
    "width": 4032,
    "height": 3024
  },
  {
    "src": "/images/new-photos/Clackamans-River-Crayfish.jpg",
    "alt": "Clackamans River Crayfish",
    "width": 4032,
    "height": 3024
  },
  {
    "src": "/images/new-photos/Cocking-lobster-mushrooms.jpg",
    "alt": "Cocking lobster mushrooms",
    "width": 4032,
    "height": 3024
  },
  {
    "src": "/images/new-photos/Crayfish.jpg",
    "alt": "Crayfish",
    "width": 4032,
    "height": 3024
  },
  {
    "src": "/images/new-photos/Daugther-Chloe-First-mate.jpg",
    "alt": "Daugther Chloe First mate",
    "width": 4032,
    "height": 3024
  },
  {
    "src": "/images/new-photos/First-and-second-mate.jpeg",
    "alt": "First and second mate",
    "width": 4032,
    "height": 3024
  },
  {
    "src": "/images/new-photos/Garden-Vegetables.jpg",
    "alt": "Garden Vegetables",
    "width": 1170,
    "height": 677
  },
  {
    "src": "/images/new-photos/Mothersday-Gravlax.jpeg",
    "alt": "Mothersday Gravlax",
    "width": 4032,
    "height": 3024
  },
  {
    "src": "/images/new-photos/Preparing-Roe.jpg",
    "alt": "Preparing Roe",
    "width": 4032,
    "height": 3024
  },
  {
    "src": "/images/new-photos/Salmon-Roe.jpg",
    "alt": "Salmon Roe",
    "width": 4032,
    "height": 3024
  },
  {
    "src": "/images/new-photos/Simple-Salmon-toast.jpg",
    "alt": "Simple Salmon toast",
    "width": 4032,
    "height": 3024
  },
  {
    "src": "/images/new-photos/Smoked-Liver-2.jpg",
    "alt": "Smoked Liver 2",
    "width": 4032,
    "height": 3024
  },
  {
    "src": "/images/new-photos/Smoked-Perfection-2.jpg",
    "alt": "Smoked Perfection 2",
    "width": 4032,
    "height": 3024
  },
  {
    "src": "/images/new-photos/Smoked-Trout.jpg",
    "alt": "Smoked Trout",
    "width": 4032,
    "height": 3024
  },
  {
    "src": "/images/new-photos/Smoked-salmon-portions.jpg",
    "alt": "Smoked salmon portions",
    "width": 2870,
    "height": 1850
  },
  {
    "src": "/images/new-photos/red-chowder-2.jpg",
    "alt": "red chowder 2",
    "width": 4032,
    "height": 3024
  },
  {
    "src": "/images/river-2687.jpg",
    "alt": "river 2687",
    "width": 2000,
    "height": 1500
  },
  {
    "src": "/images/table-3348.jpg",
    "alt": "table 3348",
    "width": 2000,
    "height": 1500
  }
]
