// Auto-generated by scripts/build-photo-wall.mjs — do not edit by hand.
export type PhotoWallImage = {
  src: string
  alt: string
  width: number
  height: number
}

export const portraitPhotos: PhotoWallImage[] = [
  {
    "src": "/images/new-photos/00-extra-photos/2-Weighting-in.jpeg",
    "alt": "Weighting in",
    "width": 1884,
    "height": 4029
  },
  {
    "src": "/images/new-photos/Catching-Crayfish.jpg",
    "alt": "Catching Crayfish",
    "width": 1500,
    "height": 2000
  },
  {
    "src": "/images/dish-3401.jpg",
    "alt": "dish 3401",
    "width": 1500,
    "height": 2000
  },
  {
    "src": "/images/dishes/plating-3164.jpg",
    "alt": "plating 3164",
    "width": 1500,
    "height": 2000
  },
  {
    "src": "/images/kitchen-3343.jpg",
    "alt": "kitchen 3343",
    "width": 1500,
    "height": 2000
  },
  {
    "src": "/images/table-3007.jpg",
    "alt": "table 3007",
    "width": 1500,
    "height": 2000
  },  {
    "src": "/images/process-3109.jpg",
    "alt": "process 3109",
    "width": 1500,
    "height": 2000
  },


]

export const landscapePhotos: PhotoWallImage[] = [
  {
    "src": "/images/catch-1346.jpg",
    "alt": "catch 1346",
    "width": 2000,
    "height": 1500
  },
  {
    "src": "/images/cured-salmon.jpg",
    "alt": "cured salmon",
    "width": 2000,
    "height": 1336
  },
  {
    "src": "/images/dish-3428.jpg",
    "alt": "dish 3428",
    "width": 1999,
    "height": 1442
  },
  {
    "src": "/images/dishes/Rainbow-trout.jpg",
    "alt": "Rainbow trout",
    "width": 4032,
    "height": 3024
  },
  {
    "src": "/images/kitchen-2620.jpg",
    "alt": "kitchen 2620",
    "width": 2000,
    "height": 1500
  },
  {
    "src": "/images/new-photos/Clackamans-River-Crayfish.jpg",
    "alt": "Clackamans River Crayfish",
    "width": 4032,
    "height": 3024
  },
  {
    "src": "/images/new-photos/Crayfish.jpg",
    "alt": "Crayfish",
    "width": 4032,
    "height": 3024
  },
  {
    "src": "/images/new-photos/Garden-Vegetables.jpg",
    "alt": "Garden Vegetables",
    "width": 1170,
    "height": 677
  },
  {
    "src": "/images/new-photos/Salmon-Roe.jpg",
    "alt": "Salmon Roe",
    "width": 4032,
    "height": 3024
  },
  {
    "src": "/images/river-2687.jpg",
    "alt": "river 2687",
    "width": 2000,
    "height": 1500
  },
  // {
  //   "src": "/images/table-3348.jpg",
  //   "alt": "table 3348",
  //   "width": 2000,
  //   "height": 1500
  // },
  {
    "src": "/images/dish-3421.jpg",
    "alt": "dish 3421",
    "width": 2000,
    "height": 1500
  },

]
